/* Crear tablespace TBSGAMARRAMARKET */
CREATE TABLESPACE TBSMARKET
DATAFILE 'tbsmarket.dbf'
SIZE 300M;

/* Permitor ejecución de script */
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

/* Crear usuario */
CREATE USER USER_ADMIN
IDENTIFIED BY root
DEFAULT TABLESPACE TBSMARKET
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON TBSMARKET;

/* Determinar los privilegios del usuario */
GRANT CREATE SESSION TO USER_ADMIN;
GRANT CREATE TABLE TO USER_ADMIN;
GRANT CREATE VIEW TO USER_ADMIN;
GRANT CREATE PROCEDURE TO USER_ADMIN;
GRANT CREATE TRIGGER TO USER_ADMIN;
GRANT CREATE SEQUENCE TO USER_ADMIN;
GRANT CREATE JOB TO USER_ADMIN;
GRANT UNLIMITED TABLESPACE TO USER_ADMIN;